### ISSUE TITLE
如何安装wcf-binary-parser==0.5.3

### ISSUE THREAD

**Issue by yaorunbang** [hebingchang/air-in-china#5]
一直显示package requirement 'wcf-binary-parser==0.5.3' is not satisfied 尝试了pip install wcf-binary-parser==0.5.3，尝试了conda install wcf，不管是哪个Python源都没能找到这个包，想问一下是怎么解决的？

**Comment by hebingchang** [comment]
python-wcfbin 这个包没进 pypi, 所以需要从 git 安装

```
pip install git+git://github.com/ernw/python-wcfbin.git
```
